import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useSelector } from "react-redux";
import ReportService from "../../../services/ReportService";
import "../../../styles/ReportListPage.css";

function ReportListPage() {
  const navigate = useNavigate();
  const { userId } = useSelector((state) => state.auth);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [filterScope, setFilterScope] = useState("ALL");

  const SCOPE_OPTIONS = ["REQUESTS", "WORK_ORDERS", "ASSETS", "MAINTENANCE"];

  // Load reports
  useEffect(() => {
    loadReports();
  }, [filterScope]);

  const loadReports = async () => {
    setLoading(true);
    setError("");
    try {
      let res;
      if (filterScope === "ALL") {
        res = await ReportService.getAll();
      } else {
        res = await ReportService.getByScope(filterScope);
      }
      setReports(res.data?.data || []);
    } catch (err) {
      setError(err.response?.data?.message || "Failed to load reports");
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (reportId) => {
    if (!window.confirm("Delete this report?")) return;
    try {
      await ReportService.remove(reportId);
      setReports(prev => prev.filter(r => r.reportId !== reportId));
    } catch (err) {
      setError(err.response?.data?.message || "Failed to delete report");
    }
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return "";
    const d = new Date(dateStr);
    return d.toLocaleDateString() + " " + d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  };

  return (
    <div className="rlist-container">
      <div className="rlist-header">
        <h1>Reports</h1>
        <button className="rlist-btn-create" onClick={() => navigate("/staff/reports/create")}>
          ➕ Create Report
        </button>
      </div>

      {error && <div className="rlist-error">{error}</div>}

      <div className="rlist-filter">
        <label>Filter by Scope:</label>
        <select value={filterScope} onChange={(e) => setFilterScope(e.target.value)}>
          <option value="ALL">All Reports</option>
          {SCOPE_OPTIONS.map(scope => (
            <option key={scope} value={scope}>{scope}</option>
          ))}
        </select>
      </div>

      {loading ? (
        <div className="rlist-loading">Loading reports...</div>
      ) : reports.length === 0 ? (
        <div className="rlist-empty">
          <p>📊 No reports found</p>
          <p>Create your first report to get started.</p>
        </div>
      ) : (
        <div className="rlist-table-wrapper">
          <table className="rlist-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Scope</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr key={report.reportId}>
                  <td>{report.reportId}</td>
                  <td><span className="rlist-badge">{report.scope}</span></td>
                  <td>User #{report.generatedBy}</td>
                  <td>{formatDate(report.generatedAt)}</td>
                  <td>
                    <button
                      className="rlist-btn-view"
                      onClick={() => navigate(`/staff/reports/${report.reportId}`)}
                    >
                      👁️ View
                    </button>
                    <button
                      className="rlist-btn-delete"
                      onClick={() => handleDelete(report.reportId)}
                    >
                      🗑️ Delete
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

export default ReportListPage;
