export const ASSET_ICON = {
  ROAD: "🛣️", BRIDGE: "🌉", FOOTPATH: "🚶", SPEED_BREAKER: "⛔",
  BUS_STOP: "🚌", PARKING_LOTS: "🅿️",
  STREET_LAMP: "💡", TRAFFIC_SIGNAL: "🚦", PEDESTRIAN_LIGHT: "🔦",
  WATER_TAP: "🚰", WATER_PIPELINE: "🔧", WATER_TANK: "🫙",
  SEWAGE: "🪣", DRAINAGE: "💧", MANHOLE: "⭕", STORM_DRAIN: "🌊",
  PUBLIC_TOILET: "🚻",
  TRANSFORMER: "⚡", ELECTRIC_POLE: "🔌", SUBSTATION: "🏭",
  PARK: "🌳", PLAYGROUND: "🎡", GARDEN: "🌺", MARKET: "🏪",
  GARBAGE_BIN: "🗑️", WASTE_COLLECTION_POINT: "♻️",
  HEALTH_CENTER: "🏥", SCHOOL_BUILDING: "🏫",
  ROAD_SIGN: "🪧", CCTV_CAMERA: "📷",
};
